namespace frameworkVisN
{
    partial class FrmMain
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.BtnGo = new System.Windows.Forms.Button();
            this.ChkAllSignals = new System.Windows.Forms.CheckedListBox();
            this.PlotFrequency = new NPlot.Windows.PlotSurface2D();
            this.PlotVoltageAngle = new NPlot.Windows.PlotSurface2D();
            this.LblPointCount = new System.Windows.Forms.Label();
            this.SuspendLayout();
            // 
            // BtnGo
            // 
            this.BtnGo.Location = new System.Drawing.Point(191, 606);
            this.BtnGo.Name = "BtnGo";
            this.BtnGo.Size = new System.Drawing.Size(75, 23);
            this.BtnGo.TabIndex = 1;
            this.BtnGo.Text = "Go";
            this.BtnGo.UseVisualStyleBackColor = true;
            this.BtnGo.Click += new System.EventHandler(this.BtnGo_Click);
            // 
            // ChkAllSignals
            // 
            this.ChkAllSignals.FormattingEnabled = true;
            this.ChkAllSignals.Location = new System.Drawing.Point(12, 26);
            this.ChkAllSignals.Name = "ChkAllSignals";
            this.ChkAllSignals.Size = new System.Drawing.Size(254, 574);
            this.ChkAllSignals.TabIndex = 2;
            this.ChkAllSignals.ItemCheck += new System.Windows.Forms.ItemCheckEventHandler(this.ChkAllSignals_ItemCheck);
            // 
            // PlotFrequency
            // 
            this.PlotFrequency.AutoScaleAutoGeneratedAxes = false;
            this.PlotFrequency.AutoScaleTitle = false;
            this.PlotFrequency.BackColor = System.Drawing.SystemColors.ControlLightLight;
            this.PlotFrequency.DateTimeToolTip = false;
            this.PlotFrequency.Location = new System.Drawing.Point(296, 26);
            this.PlotFrequency.Name = "PlotFrequency";
            this.PlotFrequency.ShowCoordinates = true;
            this.PlotFrequency.Size = new System.Drawing.Size(700, 278);
            this.PlotFrequency.SmoothingMode = System.Drawing.Drawing2D.SmoothingMode.None;
            this.PlotFrequency.TabIndex = 3;
            this.PlotFrequency.Text = "plotSurface2D1";
            this.PlotFrequency.Title = "";
            this.PlotFrequency.TitleFont = new System.Drawing.Font("Arial", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.PlotFrequency.XAxis1 = null;
            this.PlotFrequency.XAxis2 = null;
            this.PlotFrequency.YAxis1 = null;
            this.PlotFrequency.YAxis2 = null;
            this.PlotFrequency.InteractionOccured += new NPlot.Windows.PlotSurface2D.InteractionHandler(this.PlotFrequency_InteractionOccured);
            // 
            // PlotVoltageAngle
            // 
            this.PlotVoltageAngle.AutoScaleAutoGeneratedAxes = false;
            this.PlotVoltageAngle.AutoScaleTitle = false;
            this.PlotVoltageAngle.BackColor = System.Drawing.SystemColors.ControlLightLight;
            this.PlotVoltageAngle.DateTimeToolTip = false;
            this.PlotVoltageAngle.Location = new System.Drawing.Point(296, 322);
            this.PlotVoltageAngle.Name = "PlotVoltageAngle";
            this.PlotVoltageAngle.ShowCoordinates = true;
            this.PlotVoltageAngle.Size = new System.Drawing.Size(700, 278);
            this.PlotVoltageAngle.SmoothingMode = System.Drawing.Drawing2D.SmoothingMode.None;
            this.PlotVoltageAngle.TabIndex = 4;
            this.PlotVoltageAngle.Text = "plotSurface2D1";
            this.PlotVoltageAngle.Title = "";
            this.PlotVoltageAngle.TitleFont = new System.Drawing.Font("Arial", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.PlotVoltageAngle.XAxis1 = null;
            this.PlotVoltageAngle.XAxis2 = null;
            this.PlotVoltageAngle.YAxis1 = null;
            this.PlotVoltageAngle.YAxis2 = null;
            this.PlotVoltageAngle.InteractionOccured += new NPlot.Windows.PlotSurface2D.InteractionHandler(this.PlotVoltageAngle_InteractionOccured);
            // 
            // LblPointCount
            // 
            this.LblPointCount.AutoSize = true;
            this.LblPointCount.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.LblPointCount.Location = new System.Drawing.Point(313, 617);
            this.LblPointCount.Name = "LblPointCount";
            this.LblPointCount.Size = new System.Drawing.Size(118, 20);
            this.LblPointCount.TabIndex = 5;
            this.LblPointCount.Text = "Point Count:0";
            // 
            // FrmMain
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1027, 648);
            this.Controls.Add(this.LblPointCount);
            this.Controls.Add(this.PlotVoltageAngle);
            this.Controls.Add(this.PlotFrequency);
            this.Controls.Add(this.ChkAllSignals);
            this.Controls.Add(this.BtnGo);
            this.Name = "FrmMain";
            this.Text = "openVisN Framework";
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Button BtnGo;
        private System.Windows.Forms.CheckedListBox ChkAllSignals;
        private NPlot.Windows.PlotSurface2D PlotFrequency;
        private NPlot.Windows.PlotSurface2D PlotVoltageAngle;
        private System.Windows.Forms.Label LblPointCount;
    }
}

