{
 "title": "System Status",
 "time": { "from": "now-10m", "to": "now-10s" },
 "refresh": "5s",
 "panels": [
  {
   "title": "openHistorian CPU",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "queryOptions": {
      "Excluded": 0,
      "Normal": false
     },
     "queryText": "FILTER TOP 1 ActiveMeasurements WHERE PointTag LIKE '%DEFAULT!SYSTEM:ST1' "
    }
   ]
  },
  {
   "title": "openHistorian Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "queryOptions": {
      "Excluded": 0,
      "Normal": false
     },
     "queryText": "Label('openHistorian process memory', FILTER TOP 1 ActiveMeasurements WHERE PointTag LIKE '%DEFAULT!SYSTEM:ST3')"
    }
   ]
  },
  {
   "title": "openHistorian Up Time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryOptions": {
      "Excluded": 0,
      "Normal": false
     },
     "queryText": "Scale(0.01667, FILTER TOP 1 ActiveMeasurements WHERE PointTag LIKE '%DEFAULT!SYSTEM:ST15')"
    }
   ]
  },
  {
   "title": "Grafana CPU",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "queryOptions": {
      "Excluded": 0,
      "Normal": false
     },
     "queryText": "FILTER TOP 1 ActiveMeasurements WHERE PointTag LIKE '%GRAFANA!PROCESS!PROC:ST1' "
    }
   ]
  },
  {
   "title": "Grafana Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 4, "y": 7 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "queryOptions": {
      "Excluded": 0,
      "Normal": false
     },
     "queryText": "Label('Grafana process memory', FILTER TOP 1 ActiveMeasurements WHERE PointTag LIKE '%GRAFANA!PROCESS!PROC:ST2')"
    }
   ]
  },
  {
   "title": "Grafana Up Time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryOptions": {
      "Excluded": 0,
      "Normal": false
     },
     "queryText": "Scale(0.01667, FILTER TOP 1 ActiveMeasurements WHERE PointTag LIKE '%GRAFANA!PROCESS!PROC:ST3')"
    }
   ]
  },
  {
   "title": "openHistorian System Statistics",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "queryOptions": {
      "Excluded": 0,
      "Normal": false
     },
     "queryText": "Label('{Description}', FILTER ActiveMeasurements WHERE PointTag LiKE '%DEFAULT!SYSTEM:ST%' AND Description NOT LIKE '%Average%' AND Description NOT LIKE '%CPU%' AND Description NOT LIKE '%memory%' AND Description NOT LIKE '%running%')"
    }
   ]
  },
  {
   "title": "Active Input Connections",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryOptions": {
      "Excluded": 0,
      "Normal": false
     },
     "queryText": "SetSum(FILTER ActiveMeasurements WHERE PointTag LIKE '%!IS:ST8')"
    }
   ]
  },
  {
   "title": "Input Data Completeness",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "queryOptions": {
      "Excluded": 0,
      "Normal": false
     },
     "queryText": "Label('Received', SliceAvg(10, FILTER ActiveMeasurements WHERE PointTag LIKE '%!PMU:ST4'));  Label('Expected', SliceAvg(10, FILTER ActiveMeasurements WHERE PointTag LIKE '%!PMU:ST5'))"
    }
   ]
  }
 ]
}