namespace simpleVisN
{
    partial class FrmMain
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.btnOpenFile = new System.Windows.Forms.Button();
            this.btnConvertHistorianFile = new System.Windows.Forms.Button();
            this.chkAllPoints = new System.Windows.Forms.CheckedListBox();
            this.btnPlot = new System.Windows.Forms.Button();
            this.plot = new NPlot.Windows.PlotSurface2D();
            this.SuspendLayout();
            // 
            // btnOpenFile
            // 
            this.btnOpenFile.Location = new System.Drawing.Point(93, 12);
            this.btnOpenFile.Name = "btnOpenFile";
            this.btnOpenFile.Size = new System.Drawing.Size(75, 23);
            this.btnOpenFile.TabIndex = 1;
            this.btnOpenFile.Text = "Open";
            this.btnOpenFile.UseVisualStyleBackColor = true;
            this.btnOpenFile.Click += new System.EventHandler(this.btnOpenFile_Click);
            // 
            // btnConvertHistorianFile
            // 
            this.btnConvertHistorianFile.Location = new System.Drawing.Point(12, 12);
            this.btnConvertHistorianFile.Name = "btnConvertHistorianFile";
            this.btnConvertHistorianFile.Size = new System.Drawing.Size(75, 23);
            this.btnConvertHistorianFile.TabIndex = 1;
            this.btnConvertHistorianFile.Text = "Convert";
            this.btnConvertHistorianFile.UseVisualStyleBackColor = true;
            this.btnConvertHistorianFile.Click += new System.EventHandler(this.btnConvertHistorianFile_Click);
            // 
            // chkAllPoints
            // 
            this.chkAllPoints.CheckOnClick = true;
            this.chkAllPoints.FormattingEnabled = true;
            this.chkAllPoints.Location = new System.Drawing.Point(12, 56);
            this.chkAllPoints.Name = "chkAllPoints";
            this.chkAllPoints.Size = new System.Drawing.Size(257, 409);
            this.chkAllPoints.TabIndex = 2;
            // 
            // btnPlot
            // 
            this.btnPlot.Location = new System.Drawing.Point(194, 471);
            this.btnPlot.Name = "btnPlot";
            this.btnPlot.Size = new System.Drawing.Size(75, 23);
            this.btnPlot.TabIndex = 1;
            this.btnPlot.Text = "Plot";
            this.btnPlot.UseVisualStyleBackColor = true;
            this.btnPlot.Click += new System.EventHandler(this.btnPlot_Click);
            // 
            // plot
            // 
            this.plot.AutoScaleAutoGeneratedAxes = false;
            this.plot.AutoScaleTitle = false;
            this.plot.BackColor = System.Drawing.SystemColors.ControlLightLight;
            this.plot.DateTimeToolTip = true;
            this.plot.Location = new System.Drawing.Point(285, 12);
            this.plot.Name = "plot";
            this.plot.RightMenu = null;
            this.plot.ShowCoordinates = true;
            this.plot.Size = new System.Drawing.Size(820, 513);
            this.plot.SmoothingMode = System.Drawing.Drawing2D.SmoothingMode.None;
            this.plot.TabIndex = 0;
            this.plot.Text = "plotSurface2D1";
            this.plot.Title = "";
            this.plot.TitleFont = new System.Drawing.Font("Arial", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.plot.XAxis1 = null;
            this.plot.XAxis2 = null;
            this.plot.YAxis1 = null;
            this.plot.YAxis2 = null;
            // 
            // FrmMain
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1117, 537);
            this.Controls.Add(this.chkAllPoints);
            this.Controls.Add(this.btnConvertHistorianFile);
            this.Controls.Add(this.btnPlot);
            this.Controls.Add(this.btnOpenFile);
            this.Controls.Add(this.plot);
            this.Name = "FrmMain";
            this.Text = "SimpleVisN";
            this.Load += new System.EventHandler(this.FrmMain_Load);
            this.ResumeLayout(false);

        }

        #endregion

        private NPlot.Windows.PlotSurface2D plot;
        private System.Windows.Forms.Button btnOpenFile;
        private System.Windows.Forms.Button btnConvertHistorianFile;
        private System.Windows.Forms.CheckedListBox chkAllPoints;
        private System.Windows.Forms.Button btnPlot;
    }
}

